# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-185493-chris-desktop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl {
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/regs_savestates.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/EEPROM_24C0x.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/FDS.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/JYCompany.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/MMC1.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/MMC2.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/MMC3.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/MMC5.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/Namco.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/Sachen.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/Sunsoft.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/VRC.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/apu.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/cart.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/cheatcodes.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/generic.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/miracle.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/mappers/misc.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/ppu.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/savestate_ui.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/video.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/zapper.sv
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/NES.sv
    }
      rt::read_verilog -include /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl {
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.srcs/sources_1/imports/fpga/ff_sync.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.srcs/sources_1/imports/fpga/flag_sync.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.srcs/sources_1/imports/fpga/mem_example.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/nes.v
    }
      rt::read_verilog -include /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl {
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_std.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_mc.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0.v
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0_mig.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/t65/T65_Pack.vhd
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/bus_savestates.vhd
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/t65/T65_MCode.vhd
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/t65/T65_ALU.vhd
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/t65/T65.vhd
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/savestates.vhd
      /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/rtl/statemanager.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-185493-chris-desktop/realtime/emu_synth.xdc
    rt::sdcChecksum
    set rt::top emu
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-185493-chris-desktop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    rt::close_pss_mem_watcher
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
