# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/chrisnonyminus/Vivado/fpganes/fpganes.srcs/constrs_1/imports/Downloads/Nexys-A7-100T-Master.xdc

# XDC: imports/constraints/mig_7series_0.xdc

# XDC: imports/constraints/mig_7series_0_ooc.xdc

# IP: ip/mig_7series_0/mig_7series_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc

# XDC: /home/chrisnonyminus/sourcecode/fpga/NES_MiSTer/syn/NES_Mister_Nexys/NES_Mister_Nexys.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet
